name: Build Docker Image

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_protected == 'true' && github.sha || github.ref }}-{{ github.event_name }}
  cancel-in-progress: true

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add SHORT_SHA env property with commit short sha
        run: |
          SHORT_SHA=$(git rev-parse --short=9 HEAD)
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
          echo "Short SHA: $SHORT_SHA"

      - name: Set image tag based on branch
        run: |
          if [ "${{ github.ref }}" = "refs/heads/master" ]; then
            IMAGE_TAG="stellar/stellar-etl:${SHORT_SHA}"
          elif [ "${{ github.ref }}" = "refs/heads/staging" ]; then
            IMAGE_TAG="stellar/stellar-etl-staging:${SHORT_SHA}"
          else
            IMAGE_TAG="stellar/stellar-etl-dev:${SHORT_SHA}"
          fi
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "Image tag: $IMAGE_TAG"

      - name: Make docker image
        working-directory: .
        run: make docker-build
        env:
          ETLHASH: ${{ env.IMAGE_TAG }}

      - name: Login to DockerHub
        uses: docker/login-action@bb984efc561711aaa26e433c32c3521176eae55b
        with:
          username: stellardataeng
          password: ${{ secrets.DOCKER_CREDS_DEV }}

      - name: Push docker image to DockerHub
        working-directory: .
        run: docker push ${{ env.IMAGE_TAG }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/471979297599/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider"
          service_account: "acr-writer@hubble-261722.iam.gserviceaccount.com"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Google Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Tag image for Google Artifact Registry
        run: |
          if [ "${{ github.ref }}" = "refs/heads/master" ]; then
            GAR_IMAGE="us-central1-docker.pkg.dev/hubble-261722/stellar-etl/stellar-etl:${SHORT_SHA}"
          elif [ "${{ github.ref }}" = "refs/heads/staging" ]; then
            GAR_IMAGE="us-central1-docker.pkg.dev/hubble-261722/stellar-etl/stellar-etl-staging:${SHORT_SHA}"
          else
            GAR_IMAGE="us-central1-docker.pkg.dev/hubble-261722/stellar-etl/stellar-etl-dev:${SHORT_SHA}"
          fi
          docker tag ${{ env.IMAGE_TAG }} $GAR_IMAGE
          echo "GAR_IMAGE=$GAR_IMAGE" >> $GITHUB_ENV

      - name: Push docker image to Google Artifact Registry
        run: |
          docker push ${{ env.GAR_IMAGE }}
