name: Build Docker Image

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_protected == 'true' && github.sha || github.ref }}-{{ github.event_name }}
  cancel-in-progress: true

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add SHORT_SHA env property with commit short sha
        run: |
          SHORT_SHA=$(git rev-parse --short=9 HEAD)
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
          echo "Short SHA: $SHORT_SHA"

      - name: Make docker image
        working-directory: .
        run: make docker-build
        env:
          ETLHASH: stellar/stellar-etl-dev:${SHORT_SHA}

      - name: Login to DockerHub
        uses: docker/login-action@bb984efc561711aaa26e433c32c3521176eae55b
        with:
          username: stellardataeng
          password: ${{ secrets.DOCKER_CREDS_DEV }}

      - name: Push docker image to DockerHub
        working-directory: .
        run: docker push stellar/stellar-etl-dev:${SHORT_SHA}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/471979297599/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider"
          service_account: "acr-writer@hubble-261722.iam.gserviceaccount.com"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Google Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Tag image for Google Artifact Registry
        run: |
          docker tag stellar/stellar-etl-dev:${SHORT_SHA} us-central1-docker.pkg.dev/hubble-261722/stellar-etl/stellar-etl-dev:${SHORT_SHA}

      - name: Push docker image to Google Artifact Registry
        run: |
          docker push us-central1-docker.pkg.dev/hubble-261722/stellar-etl/stellar-etl-dev:${SHORT_SHA}
